// MW - Inline style objects for the web illustrator's root, canvas and
// text-editor modal.

export const webStyles = {
  root: {
    position: 'relative',
    width: '100%',
    height: '100%',
    minWidth: 1,
    minHeight: 1,
    overflow: 'hidden',
    outline: 'none',
    background: '#dfdfdf',
    touchAction: 'none',
  },
  canvas: {
    display: 'block',
    width: '100%',
    height: '100%',
    cursor: 'crosshair',
    touchAction: 'none',
  },
  loading: {
    position: 'absolute',
    inset: 0,
    display: 'grid',
    placeItems: 'center',
    color: '#334155',
    background: 'rgba(255,255,255,0.58)',
    font: '14px system-ui, sans-serif',
  },
  modalOverlay: {
    position: 'absolute',
    inset: 0,
    display: 'grid',
    placeItems: 'center',
    zIndex: 5,
  },
  modalBackdrop: {
    position: 'absolute',
    inset: 0,
    background: 'rgba(15,23,42,0.32)',
  },
  modalCard: {
    position: 'relative',
    zIndex: 1,
    width: 'min(420px, calc(100% - 32px))',
    padding: 18,
    borderRadius: 16,
    background: '#ffffff',
    boxShadow: '0 20px 60px rgba(15,23,42,0.22)',
    display: 'grid',
    gap: 12,
    fontFamily:
      'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  modalHeaderText: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  modalTitle: {
    color: '#0f172a',
    fontSize: 20,
    fontWeight: 700,
  },
  textInput: {
    width: '100%',
    boxSizing: 'border-box',
    resize: 'vertical',
    border: '1px solid #cbd5e1',
    borderRadius: 10,
    padding: 12,
    font: '15px system-ui, sans-serif',
    outline: 'none',
  },
  buttonRow: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 10,
  },
  cancelButton: {
    border: 0,
    borderRadius: 999,
    padding: '10px 16px',
    background: '#e2e8f0',
    color: '#0f172a',
    cursor: 'pointer',
  },
  submitButton: {
    border: 0,
    borderRadius: 999,
    padding: '10px 16px',
    background: '#6366f1',
    color: '#ffffff',
    cursor: 'pointer',
  },
  historyStatus: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    opacity: 0,
    pointerEvents: 'none',
  },
};
